/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulairecalcul;

/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
public class Formulaire extends javax.swing.JFrame {

    /**
     * Creates new form Formulaire
     */
    public Formulaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AnnullerBoutton = new javax.swing.JButton();
        EnregistrerButton = new javax.swing.JButton();
        ImprimerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nombre1FormattedField = new javax.swing.JFormattedTextField();
        nombre2FormattedField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Nombre 1 :");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Nombre 2 :");

        AnnullerBoutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AnnullerBoutton.setText("Annuller");
        AnnullerBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullerBouttonActionPerformed(evt);
            }
        });

        EnregistrerButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnregistrerButton.setText("Enregistrer");
        EnregistrerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerButtonActionPerformed(evt);
            }
        });

        ImprimerButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ImprimerButton.setText("Imprimer");
        ImprimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimerButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FORMULAIRE DE CALCUL DE SOMME");

        nombre1FormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        nombre2FormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AnnullerBoutton)
                        .addGap(26, 26, 26)
                        .addComponent(EnregistrerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImprimerButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombre2FormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombre1FormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre1FormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre2FormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnnullerBoutton)
                    .addComponent(EnregistrerButton)
                    .addComponent(ImprimerButton))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnullerBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullerBouttonActionPerformed
        // TODO add your handling code here:
        nombre1FormattedField.setText("");
        nombre2FormattedField.setText("");
    }//GEN-LAST:event_AnnullerBouttonActionPerformed

    private void EnregistrerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerButtonActionPerformed
        // TODO add your handling code here:
       //Récupération des champs
    String nombre1 = nombre1FormattedField.getText().trim();
    String nombre2 = nombre2FormattedField.getText().trim();

    // Vérification de saisie vide
    if (nombre1.isEmpty() || nombre2.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Veuillez remplir les deux nombres !");
        return; 
    }

    try {
        //Conversion avec remplacement de la virgule
        double n1 = Double.parseDouble(nombre1.replace(',', '.'));
        double n2 = Double.parseDouble(nombre2.replace(',', '.'));
        double somme = n1 + n2;

        //Connexion à MySQL
        String url = "jdbc:mysql://localhost:3306/iaec_2026";
        String user = "root";
        String pass = "";
        
        Connection con = DriverManager.getConnection(url, user, pass);

        //Préparer la requête SQL
        String query = "INSERT INTO Table1 (Nombre1, Nombre2, Somme) VALUES (?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(query);
        
        pst.setDouble(1, n1);
        pst.setDouble(2, n2);
        pst.setDouble(3, somme);

        //Exécution
        pst.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this, "Enregistrées avec succès !");
        
        // Fermeture
        pst.close();
        con.close();

    } catch (Exception ex) {
    // Ce bloc attrape TOUTES les erreurs (SQL, Driver, Chiffres, etc.)
    javax.swing.JOptionPane.showMessageDialog(this, "Erreur : " + ex.getMessage());
}
    }//GEN-LAST:event_EnregistrerButtonActionPerformed

    private void ImprimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimerButtonActionPerformed
        // TODO add your handling code here:
        String nombre1 = nombre1FormattedField.getText().trim();
        String nombre2 = nombre2FormattedField.getText().trim();

    if (nombre1.isEmpty() || nombre2.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erreur : Veuillez entrer des nombres dans les deux champs avant d'imprimer !", "Champs vides",
                javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    try {
        double n1 = Double.parseDouble(nombre1.replace(',', '.'));
        double n2 = Double.parseDouble(nombre2.replace(',', '.'));
        double somme = n1 + n2;
        
        String ticket = "             CALCUL\n"
                          + "--------------------------\n"
                          + " Nombre 1 : " + n1 + "\n"
                          + " Nombre 2 : " + n2 + "\n"
                          + "--------------------------\n"
                          + " SOMME    : " + somme + "\n"
                          + "--------------------------";
        javax.swing.JOptionPane.showMessageDialog(this, 
                new javax.swing.JTextArea(ticket), 
                "Impression", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            // Au cas où le format n'est pas bon
            javax.swing.JOptionPane.showMessageDialog(this, "Valeurs invalides !");
        }
    
    }//GEN-LAST:event_ImprimerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnullerBoutton;
    private javax.swing.JButton EnregistrerButton;
    private javax.swing.JButton ImprimerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField nombre1FormattedField;
    private javax.swing.JFormattedTextField nombre2FormattedField;
    // End of variables declaration//GEN-END:variables
}
