package formulairecalcul;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class Modificationdecalcul extends javax.swing.JFrame {

    /**
     * Creates new form Modificationdecalcul
     */
    public Modificationdecalcul() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        nombre1FormattedTextField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        nombre2FormattedTextField = new javax.swing.JFormattedTextField();
        Modifier = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Rechercher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MODIFICATION DE CALCUL");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Entrer id :");

        idTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Nombre 1 :");

        nombre1FormattedTextField.setEditable(false);
        nombre1FormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Nombre 2 :");

        nombre2FormattedTextField.setEditable(false);
        nombre2FormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        Modifier.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton2.setText("Enregistrer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Rechercher.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Rechercher.setText("Rechercher");
        Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre2FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre1FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Rechercher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre1FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombre2FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rechercher)
                    .addComponent(Modifier)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 44, 181, 50);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherActionPerformed
        // TODO add your handling code here:
        // 1. On récupère l'ID tapé par l'utilisateur
    String idRecherche = idTextField.getText().trim(); 

    // Vérification : l'ID ne doit pas être vide
    if (idRecherche.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez entrer un ID à rechercher !");
        return;
    }

    try {
    // 2. Connexion à la base de données
        String url = "jdbc:mysql://localhost:3306/iaec_2026";
        String user = "root";
        String pass = "";
        Connection con = DriverManager.getConnection(url, user, pass);

    // 3. Préparation de la requête SELECT
    // On cherche tout (*) là où l'id correspond au '?'
        String query = "SELECT * FROM Table1 WHERE id = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, idRecherche);

    // 4. Exécution de la requête
    // On utilise ResultSet car on attend un résultat (des données en retour)
        java.sql.ResultSet rs = pst.executeQuery();

        if (rs.next()) {
    // SI ON A TROUVÉ : On récupère les colonnes "Nombre1" et "Nombre2"
    // Et on les affiche dans tes cases de texte
            nombre1FormattedTextField.setText(rs.getString("Nombre1"));
            nombre2FormattedTextField.setText(rs.getString("Nombre2"));
            
            JOptionPane.showMessageDialog(this, "Données trouvées !");
        } else {
    // SI RIEN N'EST TROUVÉ
            JOptionPane.showMessageDialog(this, "Aucun enregistrement trouvé pour cet ID.");
    // On vide les cases par précaution
            nombre1FormattedTextField.setText("");
            nombre2FormattedTextField.setText("");
        }

    // 5. Fermeture
        rs.close();
        pst.close();
        con.close();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erreur de recherche : " + ex.getMessage());
    }
    }//GEN-LAST:event_RechercherActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        // TODO add your handling code here:
    // On permet à l'utilisateur de modifier le texte dans les cases
        nombre1FormattedTextField.setEditable(true);
        nombre2FormattedTextField.setEditable(true);
    
    // On met le curseur directement dans la première case pour gagner du temps
        nombre1FormattedTextField.requestFocus();
    
        JOptionPane.showMessageDialog(this, "Vous pouvez maintenant modifier les nombres.");
    }//GEN-LAST:event_ModifierActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // 1. On récupère l'ID et les nouvelles valeurs
    String id = idTextField.getText().trim();
    String nombre1 = nombre1FormattedTextField.getText().trim();
    String nombre2 = nombre2FormattedTextField.getText().trim();

    // Vérification : rien ne doit être vide
    if (id.isEmpty() || nombre1.isEmpty() || nombre2.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tous les champs doivent être remplis !");
        return;
    }

    try {
        // 2. Conversion et calcul de la nouvelle somme
        double n1 = Double.parseDouble(nombre1.replace(',', '.'));
        double n2 = Double.parseDouble(nombre2.replace(',', '.'));
        double nouvelleSomme = n1 + n2;

        // 3. Connexion à la base
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/iaec_2026", "root", "");

        // 4. Requête UPDATE (On met à jour Nombre1, Nombre2 et la Somme)
        String sql = "UPDATE Table1 SET Nombre1 = ?, Nombre2 = ?, Somme = ? WHERE id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        
        pst.setDouble(1, n1);
        pst.setDouble(2, n2);
        pst.setDouble(3, nouvelleSomme);
        pst.setString(4, id);

        // 5. Exécution
        int resultat = pst.executeUpdate();

        if (resultat > 0) {
            JOptionPane.showMessageDialog(this, "Modification enregistrée avec succès !");
            // On verrouille à nouveau les cases après l'enregistrement
            nombre1FormattedTextField.setEditable(false);
            nombre2FormattedTextField.setEditable(false);
        }

        pst.close();
        con.close();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erreur lors de la modification : " + ex.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificationdecalcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificationdecalcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificationdecalcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificationdecalcul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificationdecalcul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Rechercher;
    private javax.swing.JFormattedTextField idTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField nombre1FormattedTextField;
    private javax.swing.JFormattedTextField nombre2FormattedTextField;
    // End of variables declaration//GEN-END:variables
}
